apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo
  name: demo
spec:
  containers:
  - image: coffey0container/demo:latest
    name: demo
    ports:
    - containerPort: 8000
    env:
    - name: CUSTOM_NAME
      value: "Otto"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
