apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-14T15:40:50Z"
  labels:
    run: demo
  name: demo
  namespace: demo-qa
  resourceVersion: "36968"
  selfLink: /api/v1/namespaces/demo-qa/services/demo
  uid: d394cd97-5af2-420c-9d7f-5989e55483b0
spec:
  clusterIP: 10.96.110.162
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
